version: '3.7'
services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
            - "8080:8080"
            - "6001:6001"
        volumes:
            - 'nginx-conf:/etc/nginx/conf.d'
            - './network_internal.conf:/etc/nginx/network_internal.conf'
            - './proxy.conf:/etc/nginx/proxy.conf'
            - '${HOME}/letsencrypt:/etc/letsencrypt'
        depends_on:
            - dockergen
    dockergen:
        image: jwilder/docker-gen
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        restart: unless-stopped
        environment:
            ENABLE_IPV6: 'true'
        volumes:
            - 'nginx-conf:/etc/nginx/conf.d'
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - './nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl'
            - '${HOME}/letsencrypt:/etc/letsencrypt'

networks:
    default:
        external: true
        name: nginx-proxy

volumes:
    nginx-conf:
        driver: local
