services:
    nginx:
        image: nginx:${NGINX_VERSION:-1}
        container_name: nginx
        restart: always
        ports:
            - "443:443"
            - "80:80"
            - "8080:8080"
            - "6001:6001"
        volumes:
            - 'nginx-conf:/etc/nginx/conf.d'
            - './network_internal.conf:/etc/nginx/network_internal.conf'
            - './proxy.conf:/etc/nginx/proxy.conf'
            - 'letsencrypt:/etc/letsencrypt'
        networks:
            - nginx-proxy

    dockergen:
        image: jwilder/docker-gen:${DOCKERGEN_VERSION:-0.9}
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        container_name: dockergen
        restart: always
        environment:
            ENABLE_IPV6: 'true'
        volumes:
            - 'nginx-conf:/etc/nginx/conf.d'
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - './nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl'
            - 'letsencrypt:/etc/letsencrypt'
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external: true
        name: '${PROXY_NETWORK:-nginx-proxy}'
volumes:
    letsencrypt:
        external: true
        name: '${LETSENCRYPT_VOLUME:-letsencrypt}'
    nginx-conf:
        driver: local