version: '3'
services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "6001:6001"
        environment:
            ENABLE_IPV6: 'true'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - '${HOME}/letsencrypt:/etc/letsencrypt'

networks:
    default:
        external: true
        name: nginx-proxy